# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
- package-ecosystem: "github-actions" # See documentation for possible values
  directory: "/" # Location of package manifests
  schedule:
    interval: "weekly"
    time: "04:00"
  open-pull-requests-limit: 10

- package-ecosystem: "bundler" # See documentation for possible values
  directory: "/updater" # Location of package manifests
  schedule:
    interval: "weekly"
    time: "04:00"
  open-pull-requests-limit: 10

- package-ecosystem: "docker" # See documentation for possible values
  directory: "/" # Location of package manifests
  schedule:
    interval: "weekly"
    time: "04:00"
  open-pull-requests-limit: 10

- package-ecosystem: "nuget" # See documentation for possible values
  directory: "/" # Location of package manifests
  schedule:
    interval: "weekly"
    time: "02:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "Microsoft.*"
    update-types: ["version-update:semver-patch"]
  - dependency-name: "System.*"
    update-types: ["version-update:semver-patch"]
  - dependency-name: "Azure.*"
    update-types: ["version-update:semver-patch"]
  - dependency-name: "Moq"
    update-types: ["version-update:semver-patch"]

- package-ecosystem: "npm" # See documentation for possible values
  directory: "/extension" # Location of package manifests
  schedule:
    interval: "weekly"
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "axios"
    update-types: ["version-update:semver-patch"]
  - dependency-name: "jest"
    update-types: ["version-update:semver-patch"]
  - dependency-name: "@types/node"
    update-types: ["version-update:semver-patch"]

registries:
  tingle:
    type: nuget-feed
    url: 'https://pkgs.dev.azure.com/tingle/_packaging/tingle/nuget/v3/index.json'
    token: '${{ secrets.TINGLE_NUGET_FEED_KEY }}'
