name: Cleanup

on:
  workflow_dispatch:
  schedule:
  - cron: '0 0 */14 * *' # every 14 days

jobs:
  cleanup-updater:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        suite:
        - { name: bundler }
        - { name: cargo }
        - { name: composer }
        - { name: docker }
        - { name: elm }
        - { name: gitsubmodule }
        - { name: github-actions }
        - { name: gomod }
        - { name: gradle }
        - { name: mix }
        - { name: maven }
        - { name: npm }
        - { name: nuget }
        - { name: pub }
        - { name: pip }
        # TODO: restore swift here once supported elsewhere
        # - { name: swift }
        - { name: terraform }

    steps:
    - name: Delete old dependabot-updater-${{ matrix.suite.ecosystem }} images
      uses: actions/delete-package-versions@v4
      with:
        package-name: 'dependabot-updater-${{ matrix.suite.ecosystem }}'
        package-type: 'container'
        min-versions-to-keep: 20
        delete-only-pre-release-versions: "true"

  cleanup-server:
    runs-on: ubuntu-latest

    steps:
    - name: Delete old dependabot-server images
      uses: actions/delete-package-versions@v4
      with:
        package-name: 'dependabot-server'
        package-type: 'container'
        min-versions-to-keep: 20
        delete-only-pre-release-versions: "true"
