name: Docker

on:
  push:
    branches:
    - main
    tags:
    - '*'
    paths:
    - "script/**"
    - "Dockerfile"
    - ".github/workflows/docker.yml"
    - "!docs/**"
  pull_request:
    branches:
    # Only trigger for PRs against `main` branch.
    - main
    paths:
    - "script/**"
    - "Dockerfile"
    - ".github/workflows/docker.yml"
    - "!docs/**"

jobs:
  dockerize:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: 'dependabot-azure-devops'
      DOCKER_BUILDKIT: 1 # Enable Docker BuildKit
      # $BUNDLE_GEMFILE must be set at the job level, so it is set for all steps
      BUNDLE_GEMFILE: ${{ github.workspace }}/updater/Gemfile

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Required for GitVersion
        submodules: true

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'

    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0
      with:
        useConfigFile: true

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: bundle exec rubocop
      run: bundle exec rubocop
      working-directory: updater

    - name: bundle exec rspec spec
      run: bundle exec rspec spec
      working-directory: updater

    - name: Pull Docker base image & warm Docker cache
      run: docker pull "tingle/$IMAGE_NAME:latest"

    - name: Build image
      run: |
        docker build \
        -f Dockerfile \
        -t "tingle/$IMAGE_NAME:latest" \
        -t "tingle/$IMAGE_NAME:$GITVERSION_FULLSEMVER" \
        -t "tingle/$IMAGE_NAME:$GITVERSION_MAJOR.$GITVERSION_MINOR" \
        -t "tingle/$IMAGE_NAME:$GITVERSION_MAJOR" \
        --cache-from tingle/$IMAGE_NAME:latest \
        --build-arg BUILDKIT_INLINE_CACHE=1 \
        .

    - name: Log into registry (Docker Hub)
      if: ${{ (github.ref == 'refs/heads/main') || (!startsWith(github.ref, 'refs/pull')) || startsWith(github.ref, 'refs/tags') }}
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push image to Docker Hub (latest)
      if: github.ref == 'refs/heads/main'
      run: docker push "tingle/$IMAGE_NAME:latest"

    - name: Push image to Docker Hub (FullSemVer)
      if: "!startsWith(github.ref, 'refs/pull')"
      run: docker push "tingle/$IMAGE_NAME:$GITVERSION_FULLSEMVER"

    - name: Push image to Docker Hub (major, minor)
      if: startsWith(github.ref, 'refs/tags')
      run: |
        docker push "tingle/$IMAGE_NAME:$GITVERSION_MAJOR.$GITVERSION_MINOR"
        docker push "tingle/$IMAGE_NAME:$GITVERSION_MAJOR"
